import { chromium } from 'playwright';
import { resolve } from 'node:path';

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setContent(`<!doctype html><html><head><meta charset="utf-8"><style>
@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#10182b;margin:0;font-size:10.5pt;line-height:1.38}h1{font-size:29pt;margin:0;color:#071127}h2{font-size:12pt;text-transform:uppercase;letter-spacing:.12em;color:#315db7;border-bottom:1px solid #cbd6ec;padding-bottom:4px;margin:18px 0 8px}h3{font-size:11pt;margin:10px 0 1px}.lead{font-size:12pt;color:#3e4a63;margin:4px 0}.meta{color:#52617d}.row{display:flex;justify-content:space-between;gap:12px}.row strong{color:#16284d}ul{margin:4px 0 8px;padding-left:17px}.tags{color:#263a67}.small{font-size:9pt}a{color:#244f9e;text-decoration:none}</style></head><body>
<h1>David Puentes</h1><p class="lead">Full-Stack Software Developer · Data Analyst · IoT & Applied AI Builder</p><p class="meta">Bogotá, Colombia · <a href="https://github.com/DavidSPuentesc">github.com/DavidSPuentesc</a></p>
<h2>Profile</h2><p>Engineer-minded developer building web products, data workflows, connected electronics, and applied AI systems. Experience spans TypeScript, React, Python, SQL, Docker, ESP32, LoRa, scientific computing, computer vision, and agentic workflows with skills, subagents, context control, token budgets, traceability, and human validation.</p>
<h2>Experience</h2><div class="row"><h3>Full-Stack Software Developer & Data Analyst · PRLCOL</h3><span>Aug 2025—Present</span></div><ul><li>Develop and support complete modules for a multi-instance B2B SaaS platform.</li><li>Work across SQL migrations, automation, telemetry, integrations, and applied AI.</li></ul><div class="row"><h3>Research & Development Developer · Universidad ECCI / CEINTECCI</h3><span>Jun 2024—Jun 2025</span></div><ul><li>Built reproducible scientific-computing pipelines for stylometric analysis over approximately two million syllables.</li><li>Supported technical communication and research dissemination.</li></ul>
<h2>Selected Projects</h2><h3>SmartSense Monitoring</h3><p>Industrial thermal monitoring with PT100, ESP32-C6, LoRa, local storage, and dashboard. More than 51,000 samples recorded; a 688 m obstructed field link was demonstrated.</p><h3>SecurApp</h3><p>Software and applied-AI work involving orchestration, specialized agents and subagents, reusable skills, context and token management, and human-reviewed outcomes.</p><h3>Electronics, sensing & scientific systems</h3><p>Projects involving Wi-Fi sensing, sensor dashboards, ESP32 firmware, computer vision, scientific simulation, and data analysis.</p>
<h2>Technical Skills</h2><p class="tags"><strong>AI & automation:</strong> agent orchestration, subagents, skills, RAG, prompt design, token budgeting, computer vision<br><strong>Software & data:</strong> TypeScript, React, Python, Django, Flask, SQL, REST APIs, Docker<br><strong>Electronics & IoT:</strong> ESP32, C++, LoRa, BLE, PT100, sensors, instrumentation, Edge AI<br><strong>Infrastructure & security:</strong> Terraform, AWS, CI/CD, observability, cybersecurity and privacy</p>
<h2>Certifications</h2><p class="small">AI Application Development · React.js with TypeScript · TypeScript · Terraform · Cybersecurity and Privacy for Businesses — Platzi (2026)<br>Scientific Computing with Python · Responsive Web Design — freeCodeCamp (2025)</p>
</body></html>`, { waitUntil: 'load' });
await page.pdf({ path: resolve('public/cv/david-puentes-cv-en.pdf'), format: 'A4', printBackground: true });
await browser.close();
